### ISSUE TITLE
能否给下建表SQL

### ISSUE THREAD

**Issue by hwy110** [wiselyman/uaa-zuul#7]
能否给下建表SQL

**Comment by KumaNeko33** [comment]
同求

**Comment by nieli** [comment]
配置好datasource 表是自动创建的

**Comment by wiselyman** [comment]
@hwy110 @KumaNeko33 @nieli 
```
  jpa:
    open-in-view: true
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
```
表结构是hibernate自动按照实体类建的。
